const FILTERS={subjects:{select:document.querySelector('#filterSubjects'),values:['Character Studies','Death Culture','Belief & Divination','Religious Practice','Performance','Institutional Life','Roadside America','Material Culture','Maintenance & Service Work','Occupational Life']},imageStyle:{select:document.querySelector('#filterImageStyle'),values:['B&W','Color','Sepia','Tintype','Mixed','Unknown']},locationType:{select:document.querySelector('#filterLocationType'),values:['Studio','Interior','Exterior','Unknown']},continent:{select:document.querySelector('#filterContinent'),values:['North America','South America','Europe','Africa','Asia','Antarctica','Unknown']},shot:{select:document.querySelector('#filterShot'),values:['Close','Medium','Wide','Unknown']}};
const SOURCE={url:'data/archive-data.json',backupUrl:'data/archive-backup.json',grid:document.querySelector('#archiveGrid'),count:document.querySelector('#archiveCount'),search:document.querySelector('#archiveSearch'),pagination:document.querySelector('#archivePagination'),empty:'No approved archive records yet.'};
const LIGHTBOX={wrap:document.querySelector('#cardLightbox'),card:document.querySelector('#lightboxCard'),close:document.querySelector('.lightbox-close'),prev:document.querySelector('.lightbox-prev'),next:document.querySelector('.lightbox-next')};
const REPO_ISSUES_URL='https://github.com/unlikely-archivist/Lantern/issues/new';
const CURATION_ACTIONS=['Like','Add','More Like','Not For Me','Flag'];
const PER_PAGE=24;
const state={rows:[],page:1,visibleRows:[],lightboxIndex:0};
function norm(v){return String(v||'').trim()}function esc(v){return String(v).replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}function attr(v){return esc(v).replace(/'/g,'&#39;')}function tag(t){const v=norm(t);return v?(v.startsWith('#')?v:`#${v}`):''}function list(v){if(Array.isArray(v))return v.map(norm).filter(Boolean);if(typeof v==='string')return v.split(',').map(norm).filter(Boolean);return[]}function tags(v){return list(v).map(tag).filter(Boolean)}
function people(v){const n=norm(v).toLowerCase();if(!n)return'Unknown';if(['none','no people','0'].includes(n))return'None';if(['single','one','one person','1'].includes(n))return'One Person';if(['pair','two','two people','2'].includes(n))return'Two People';if(['multi','multiple','group','small group'].includes(n))return'Small Group';if(['crowd','crowded'].includes(n))return'Crowd';return v||'Unknown'}
function period(r){const e=r.time_period||r.timePeriod||r.period;if(e)return e;const y=Number(String(r.date||r.originalDate||r.year||'').match(/\d{4}/)?.[0]);if(!y)return'Unknown';if(y<1800)return'Pre-1800';if(y<=1849)return'1800–1849';if(y<=1899)return'1850–1899';if(y<=1919)return'1900–1919';if(y<=1939)return'1920–1939';if(y<=1959)return'1940–1959';if(y<=1979)return'1960–1979';if(y<=1999)return'1980–1999';return'2000–Present'}
function subjects(r,t){const text=[r.title,r.caption,r.notes,r.description,...t].join(' ').toLowerCase();const s=new Set(list(r.subjects||r.subject));if(/character|portrait|fortune|guard|keeper|attendant/.test(text))s.add('Character Studies');if(/work|labor|attendant|guard|service|operator|maker|keeper/.test(text))s.add('Occupational Life');if(/religion|ritual|baptism|temple|shrine|preacher/.test(text))s.add('Religious Practice');if(/fortune|divination|occult|spiritual/.test(text))s.add('Belief & Divination');if(/fair|roadside|service station|louisiana/.test(text))s.add('Roadside America');return[...s]}
function rec(r){const t=tags(r.final_tags||r.finalTags||r.tags);return{title:r.title||r.name||'Untitled record',medium:r.medium||r.media||'Photography',imgSrc:r.imgSrc||r.imageUrl||r.image_url||r.thumbnail||'',sourceUrl:r.sourceUrl||r.source_url||r.url||'',dateAdded:r.dateAdded||r.date_added||'',sortDate:Date.parse(r.dateAdded||r.date_added||r.date||'')||0,subjects:subjects(r,t),tags:t,caption:r.caption||r.notes||r.description||'',imageStyle:r.image_style||r.imageStyle||r.color||'Unknown',peopleCount:people(r.people_count||r.peopleCount||r.people),shot:r.shot||'Unknown',locationType:r.location_type||r.locationType||r.loc||'Unknown',continent:r.continent||'Unknown',timePeriod:period(r),sourceId:r.source_id||r.sourceId||'',collectionTitle:r.collection_title||r.collectionTitle||'',sourceType:r.source_type||r.sourceType||''}}
async function getJson(url){const res=await fetch(`${url}?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(res.status);return res.json()}
async function load(){try{let data=await getJson(SOURCE.url);if(Array.isArray(data)&&data.length===0&&SOURCE.backupUrl)data=await getJson(SOURCE.backupUrl);return Array.isArray(data)?data.map(rec).sort((a,b)=>b.sortDate-a.sortDate||a.title.localeCompare(b.title)):[]}catch(e){console.warn('Could not load archive',e);if(SOURCE.backupUrl){try{const data=await getJson(SOURCE.backupUrl);return Array.isArray(data)?data.map(rec).sort((a,b)=>b.sortDate-a.sortDate||a.title.localeCompare(b.title)):[]}catch(err){console.warn('Could not load archive backup',err)}}return[]}}
function searchable(r){return[r.title,r.medium,r.caption,r.imageStyle,r.peopleCount,r.shot,r.locationType,r.continent,r.timePeriod,r.collectionTitle,...r.subjects,...r.tags].join(' ').toLowerCase()}
function selected(k){return FILTERS[k]?.select?.value||''}function match(r,k,v){if(!v)return true;const val=r[k];return Array.isArray(val)?val.includes(v):val===v}
function filtered(){const q=SOURCE.search?.value.trim().toLowerCase()||'';return state.rows.filter(r=>(!q||searchable(r).includes(q))&&Object.keys(FILTERS).every(k=>match(r,k,selected(k))))}
function renderFilters(){Object.entries(FILTERS).forEach(([k,f])=>{if(!f.select)return;const first=f.select.querySelector('option')?.textContent||'';const av=new Set();state.rows.forEach(r=>{const v=r[k];Array.isArray(v)?v.forEach(x=>av.add(x)):v&&av.add(v)});const vals=f.values.filter(v=>av.has(v));f.select.innerHTML=`<option value="">${esc(first)}</option>`+vals.map(v=>`<option value="${attr(v)}">${esc(v)}</option>`).join('');f.select.addEventListener('change',()=>{state.page=1;render()})})}
function issueUrl(action,r){const fullAction={Add:'Add to Art Gallery','More Like':'More Like This'}[action]||action;const title=`[${fullAction}] ${r.title}`;const body=[`Action: ${fullAction}`,`Section: archive`,`Title: ${r.title}`,`Source URL: ${r.sourceUrl||'—'}`,`Image URL: ${r.imgSrc||'—'}`,`Collection: ${r.collectionTitle||'—'}`,`Source ID: ${r.sourceId||'—'}`,`Tags: ${r.tags.join(' ')||'—'}`,`Caption: ${r.caption||'—'}`].join('\n');return`${REPO_ISSUES_URL}?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`}
function actionButtons(r){return`<div class="card-actions" aria-label="Curation actions">${CURATION_ACTIONS.map(a=>`<a class="card-action" href="${attr(issueUrl(a,r))}" target="_blank" rel="noreferrer">${esc(a)}</a>`).join('')}</div>`}
function captionBlock(r,big=false){if(!r.caption)return'';if(big)return`<p class="card-caption is-full">${esc(r.caption)}</p>`;return`<button type="button" class="card-caption caption-trigger" data-caption="${attr(r.caption)}" aria-label="Read full caption">${esc(r.caption)}</button>`}
function cardInner(r,big=false){const tg=r.tags.slice(0,big?12:6).map(t=>`<a class="tag-pill" href="index.html?tag=${encodeURIComponent(t)}#archive">${esc(t)}</a>`).join('');const img=r.imgSrc?`<img src="${attr(r.imgSrc)}" alt="${attr(r.title)}" loading="lazy" referrerpolicy="no-referrer"/>`:'<div class="img-fallback">No image yet</div>';const source=r.sourceUrl?`<a class="card-link" href="${attr(r.sourceUrl)}" target="_blank" rel="noreferrer">Open source</a>`:'';const meta=[r.imageStyle,r.locationType,r.continent,r.timePeriod,r.collectionTitle].filter(v=>v&&v!=='Unknown').join(' | ');return`<div class="card-img-wrap">${img}</div><div class="card-body"><h3 class="card-title">${esc(r.title)}</h3>${captionBlock(r,big)}${tg?`<div class="card-tags">${tg}</div>`:''}${meta?`<p class="card-meta">${esc(meta)}</p>`:''}${actionButtons(r)}${source}</div>`}
function card(r,index){return`<article class="card" data-card-index="${index}" tabindex="0" role="button" aria-label="Enlarge ${attr(r.title)}">${cardInner(r)}</article>`}
function showCaption(text){let pop=document.querySelector('#captionPopover');if(!pop){pop=document.createElement('div');pop.id='captionPopover';pop.className='caption-popover';pop.innerHTML='<button type="button" aria-label="Close caption">×</button><p></p>';document.body.appendChild(pop);pop.querySelector('button').addEventListener('click',()=>pop.hidden=true);pop.addEventListener('click',e=>{if(e.target===pop)pop.hidden=true})}pop.querySelector('p').textContent=text;pop.hidden=false}
function openLightbox(index){if(!state.visibleRows.length)return;state.lightboxIndex=(index+state.visibleRows.length)%state.visibleRows.length;const r=state.visibleRows[state.lightboxIndex];LIGHTBOX.card.innerHTML=`<article class="card card-large">${cardInner(r,true)}</article>`;LIGHTBOX.wrap.hidden=false;document.body.classList.add('lightbox-open');LIGHTBOX.close.focus()}
function closeLightbox(){LIGHTBOX.wrap.hidden=true;document.body.classList.remove('lightbox-open')}
function moveLightbox(delta){openLightbox(state.lightboxIndex+delta)}
function renderPagination(total){const pages=Math.max(1,Math.ceil(total/PER_PAGE));state.page=Math.min(state.page,pages);if(pages<=1){SOURCE.pagination.innerHTML='';return}const nums=[];for(let i=1;i<=pages;i++){if(i===1||i===pages||Math.abs(i-state.page)<=2)nums.push(i)}let last=0;SOURCE.pagination.innerHTML=`<button type="button" data-page="${state.page-1}" ${state.page===1?'disabled':''}>Prev</button>`+nums.map(n=>{const gap=n-last>1?'<span>…</span>':'';last=n;return gap+`<button type="button" class="${n===state.page?'is-current':''}" data-page="${n}">${n}</button>`}).join('')+`<button type="button" data-page="${state.page+1}" ${state.page===pages?'disabled':''}>Next</button>`;SOURCE.pagination.querySelectorAll('button[data-page]').forEach(b=>b.addEventListener('click',()=>{const p=Number(b.dataset.page);if(p>=1&&p<=pages){state.page=p;render();document.querySelector('#archive').scrollIntoView({behavior:'smooth'})}}))}
function render(){const rows=filtered();state.visibleRows=rows;const start=(state.page-1)*PER_PAGE;const shown=rows.slice(start,start+PER_PAGE);SOURCE.count.textContent=`${rows.length} shown / ${state.rows.length} total · Page ${Math.min(state.page,Math.max(1,Math.ceil(rows.length/PER_PAGE)))} of ${Math.max(1,Math.ceil(rows.length/PER_PAGE))}`;SOURCE.grid.innerHTML=shown.length?shown.map((r,i)=>card(r,start+i)).join(''):`<div class="empty-state">${SOURCE.empty}</div>`;SOURCE.grid.querySelectorAll('.card[data-card-index]').forEach(el=>{el.addEventListener('click',e=>{const cap=e.target.closest('.caption-trigger');if(cap){e.stopPropagation();showCaption(cap.dataset.caption||cap.textContent);return}if(e.target.closest('a,button'))return;openLightbox(Number(el.dataset.cardIndex))});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLightbox(Number(el.dataset.cardIndex))}})});renderPagination(rows.length)}
function reset(){SOURCE.search.value='';Object.values(FILTERS).forEach(f=>{if(f.select)f.select.value=''});state.page=1;render()}
function applyTag(){const t=new URLSearchParams(location.search).get('tag');if(!t)return;SOURCE.search.value=tag(t)}
function setupLightbox(){LIGHTBOX.close?.addEventListener('click',closeLightbox);LIGHTBOX.prev?.addEventListener('click',()=>moveLightbox(-1));LIGHTBOX.next?.addEventListener('click',()=>moveLightbox(1));LIGHTBOX.wrap?.addEventListener('click',e=>{if(e.target===LIGHTBOX.wrap)closeLightbox()});document.addEventListener('keydown',e=>{if(document.querySelector('#captionPopover:not([hidden])')&&e.key==='Escape'){document.querySelector('#captionPopover').hidden=true;return}if(LIGHTBOX.wrap?.hidden)return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')moveLightbox(-1);if(e.key==='ArrowRight')moveLightbox(1)})}
async function init(){state.rows=await load();renderFilters();applyTag();SOURCE.search?.addEventListener('input',()=>{state.page=1;render()});document.querySelector('[data-reset="archive"]')?.addEventListener('click',reset);setupLightbox();render()}init();
